services:

  postgres:
    container_name: app-postgres
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-Azerty123_}
      POSTGRES_DB: ${POSTGRES_ADMIN_DB:-postgres}
    networks:
      - app-network
    ports:
      - 0.0.0.0:5432:5432/tcp
    healthcheck:
      test: "pg_isready -U ${POSTGRES_ADMIN_USER:-admin} -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-post-install-job:
    container_name: app-postgres-post-install-job
    image: mirror.gcr.io/postgres:15.12-alpine3.20
    volumes:
      - ./postgres-post-install-job/create_env.sh:/usr/local/bin/create_env.sh
    environment:
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER:-admin}
      PGPASSWORD: ${POSTGRES_ADMIN_PASSWORD:-Azerty123_}
      POSTGRES_KEYCLOAK_USER: ${POSTGRES_KEYCLOAK_USER:-keycloak_db_user}
      POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:-Azerty123_}
      POSTGRES_KEYCLOAK_DB: ${POSTGRES_KEYCLOAK_DB:-keycloak}
      POSTGRES_FRED_USER: ${POSTGRES_FRED_USER:-fred}
      POSTGRES_FRED_PASSWORD: ${POSTGRES_FRED_PASSWORD:-Azerty123_}
      POSTGRES_FRED_DB: ${POSTGRES_FRED_DB:-fred}
      POSTGRES_TABULAR_DATA_USER: ${POSTGRES_TABULAR_DATA_USER:-tabular}
      POSTGRES_TABULAR_DATA_PASSWORD: ${POSTGRES_TABULAR_DATA_PASSWORD:-Azerty123_}
      POSTGRES_TABULAR_DATA_DB: ${POSTGRES_TABULAR_DATA_DB:-data}
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |-
        create_env.sh \
          --admin "$$POSTGRES_ADMIN_USER" \
          --host "app-postgres" \
          --user "$$POSTGRES_KEYCLOAK_USER" \
          --password "$$POSTGRES_KEYCLOAK_PASSWORD" \
          --database "$$POSTGRES_KEYCLOAK_DB" \
          --enable-vector
        create_env.sh \
          --admin "$$POSTGRES_ADMIN_USER" \
          --host "app-postgres" \
          --user "$$POSTGRES_FRED_USER" \
          --password "$$POSTGRES_FRED_PASSWORD" \
          --database "$$POSTGRES_FRED_DB" \
          --enable-vector
        create_env.sh \
          --admin "$$POSTGRES_ADMIN_USER" \
          --host "app-postgres" \
          --user "$$POSTGRES_TABULAR_DATA_USER" \
          --password "$$POSTGRES_TABULAR_DATA_PASSWORD" \
          --database "$$POSTGRES_TABULAR_DATA_DB" \
          --enable-vector
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      
  keycloak:
    container_name: app-keycloak
    image: mirror.gcr.io/keycloak/keycloak:26.3.0
    environment:
      KC_HTTP_ENABLE: true
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_DB: ${POSTGRES_ADMIN_DB:-postgres}
      KC_DB_URL: jdbc:postgresql://app-postgres:5432/${POSTGRES_KEYCLOAK_DB:-keycloak}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER:-keycloak_db_user}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:-Azerty123_}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-Azerty123_}
      DOCKER_COMPOSE_HOST_FQDN: ${DOCKER_COMPOSE_HOST_FQDN:-localhost}
      TEMPORAL_UI_PORT: ${TEMPORAL_UI_PORT:-8233}
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |-
        [ ! -d /opt/keycloak/data/import ] && mkdir -p /opt/keycloak/data/import
        sed "s#__DOCKER_COMPOSE_HOST_FQDN__#$$DOCKER_COMPOSE_HOST_FQDN#g; s#__TEMPORAL_UI_PORT__#$$TEMPORAL_UI_PORT#g" /tmp/app-realm.json.template > /opt/keycloak/data/import/app-realm.json
        /opt/keycloak/bin/kc.sh start-dev --import-realm
    volumes:
      - ./keycloak/app-realm.json.template:/tmp/app-realm.json.template
      - ./keycloak/realm_export:/export
    networks:
      app-network:
        aliases:
          - ${DOCKER_COMPOSE_HOST_FQDN:-"app-keycloak"}
    ports:
      - 0.0.0.0:8080:8080/tcp
    depends_on:
      postgres-post-install-job:
        condition: service_completed_successfully
    healthcheck:
      test: /opt/keycloak/bin/kcadm.sh get realms/app --fields id --server http://localhost:8080 --realm master --user $$KC_BOOTSTRAP_ADMIN_USERNAME --password $$KC_BOOTSTRAP_ADMIN_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 10s

networks:
  app-network:
    external: true
    name: fred-shared-network
