services:

  postgres:
    container_name: app-postgres
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-Azerty123_}
      POSTGRES_DB: ${POSTGRES_ADMIN_DB:-postgres}
    networks:
      - app-network
    ports:
      - 127.0.0.1:5432:5432/tcp
    healthcheck:
      test: "pg_isready -U ${POSTGRES_ADMIN_USER:-admin} -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-post-install-job:
    container_name: app-postgres-post-install-job
    image: mirror.gcr.io/postgres:15.12-alpine3.20
    volumes:
      - ./postgres-post-install-job/create_env.sh:/usr/local/bin/create_env.sh
    environment:
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER:-admin}
      PGPASSWORD: ${POSTGRES_ADMIN_PASSWORD:-Azerty123_}
      POSTGRES_FRED_USER: ${POSTGRES_FRED_USER:-fred}
      POSTGRES_FRED_PASSWORD: ${POSTGRES_FRED_PASSWORD:-Azerty123_}
      POSTGRES_FRED_DB: ${POSTGRES_FRED_DB:-fred}
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |-
        create_env.sh \
          --admin "$$POSTGRES_ADMIN_USER" \
          --host "app-postgres" \
          --user "$$POSTGRES_FRED_USER" \
          --password "$$POSTGRES_FRED_PASSWORD" \
          --database "$$POSTGRES_FRED_DB" \
          --enable-vector
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  app-network:
    external: true
    name: fred-shared-network
