apiVersion: v1
kind: Secret
metadata:
  name: fred-secrets
  labels:
    {{- include "fred-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_ADMIN_USER: {{ .Values.auth.postgresAdminUser | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ .Values.auth.postgresAdminPassword | quote }}

  POSTGRES_KEYCLOAK_USER: {{ .Values.auth.postgresKeycloakUser | quote }}
  POSTGRES_KEYCLOAK_PASSWORD: {{ .Values.auth.postgresKeycloakPassword | quote }}
  POSTGRES_KEYCLOAK_DB: {{ .Values.auth.postgresKeycloakDb | quote }}

  POSTGRES_FRED_USER: {{ .Values.auth.postgresFredUser | quote }}
  POSTGRES_FRED_PASSWORD: {{ .Values.auth.postgresFredPassword | quote }}
  POSTGRES_FRED_DB: {{ .Values.auth.postgresFredDb | quote }}

  POSTGRES_TABULAR_DATA_USER: {{ .Values.auth.postgresTabularUser | quote }}
  POSTGRES_TABULAR_DATA_PASSWORD: {{ .Values.auth.postgresTabularPassword | quote }}
  POSTGRES_TABULAR_DATA_DB: {{ .Values.auth.postgresTabularDb | quote }}

  POSTGRES_OPENFGA_USER: {{ .Values.auth.postgresOpenfgaUser | quote }}
  POSTGRES_OPENFGA_PASSWORD: {{ .Values.auth.postgresOpenfgaPassword | quote }}
  POSTGRES_OPENFGA_DBNAME: {{ .Values.auth.postgresOpenfgaDb | quote }}

  POSTGRES_TEMPORAL_USER: {{ .Values.auth.postgresTemporalUser | quote }}
  POSTGRES_TEMPORAL_PASSWORD: {{ .Values.auth.postgresTemporalPassword | quote }}
  POSTGRES_TEMPORAL_DBNAME: {{ .Values.auth.postgresTemporalDb | quote }}
  POSTGRES_TEMPORAL_VISIBILITY_DBNAME: {{ .Values.auth.postgresTemporalVisibilityDb | quote }}

  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.auth.keycloakAdminUser | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.auth.keycloakAdminPassword | quote }}
  KEYCLOAK_AGENTIC_CLIENT_SECRET: {{ .Values.auth.keycloakAgenticClientSecret | quote }}
  KEYCLOAK_KNOWLEDGE_FLOW_CLIENT_SECRET: {{ .Values.auth.keycloakKnowledgeFlowClientSecret | quote }}
  KEYCLOAK_KF_ENABLE_MANAGE_USERS: {{ .Values.auth.keycloakKfEnableManageUsers | quote }}
  KEYCLOAK_FORCE_RELOGIN: {{ .Values.auth.keycloakForceRelogin | quote }}

  MINIO_ROOT_USER: {{ .Values.auth.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.auth.minioRootPassword | quote }}
  MINIO_READONLY_USER: {{ .Values.auth.minioReadonlyUser | quote }}
  MINIO_READONLY_PASSWORD: {{ .Values.auth.minioReadonlyPassword | quote }}
  MINIO_READWRITE_USER: {{ .Values.auth.minioReadwriteUser | quote }}
  MINIO_READWRITE_PASSWORD: {{ .Values.auth.minioReadwritePassword | quote }}

  OPENSEARCH_ADMIN: {{ .Values.auth.opensearchAdminUser | quote }}
  OPENSEARCH_ADMIN_PASSWORD: {{ .Values.auth.opensearchAdminPassword | quote }}

  OPENFGA_API_TOKEN: {{ .Values.auth.openfgaApiToken | quote }}
  OPENFGA_STORE_NAME: {{ .Values.auth.openfgaStoreName | quote }}
  OPENFGA_SEED_INCLUDE_USERNAME_USERS: {{ .Values.auth.openfgaSeedIncludeUsernameUsers | quote }}
